version: 0.2

phases:
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f5t0r4g8
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build -t flaskapp:$IMAGE_TAG .
      - docker tag flaskapp:$IMAGE_TAG public.ecr.aws/f5t0r4g8/flaskapp:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/f5t0r4g8/flaskapp:$IMAGE_TAG
      - printf '[{"name":"sharma-assignment3-container","imageUri":"%s"}]' public.ecr.aws/f5t0r4g8/flaskapp:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
